package com.subsystems;

import com.broker.AsyncMessageBroker;
import com.broker.EventType;
import com.broker.Listener;
import com.broker.Message;
import com.common.dto.wishlist.WishlistAddRequest;
import com.common.dto.wishlist.WishlistRemoveRequest;
import com.common.dto.wishlist.WishlistViewRequest;
import com.entities.Item;
import com.entities.Wishlist;
import com.repository.ItemRepository;
import com.repository.WishlistRepository;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import java.util.logging.Logger;

/**
 * WishlistManagement
 * -------------------------------------------------------
 * - Add item to wishlist (with stock & unique constraint)
 * - Remove item
 * - View wishlist
 * - Emits async events through broker
 *
 * NOTE:
 * Current implementation uses in-memory list as placeholder.
 * Replace with Database repo when integrating SQLite.
 */

public class WishlistManagement implements Subsystems {

    private static final Logger LOGGER = Logger.getLogger(WishlistManagement.class.getName());

    private AsyncMessageBroker broker;
    private WishlistRepository wishlistRepo;
    private ItemRepository itemRepo;

    private final Listener handleAdd = this::onAddRequested;
    private final Listener handleRemove = this::onRemoveRequested;
    private final Listener handleView = this::onViewRequested;

    public WishlistManagement(WishlistRepository wishlistRepo, ItemRepository itemRepo) {
        this.wishlistRepo = wishlistRepo;
        this.itemRepo = itemRepo;
    }

    @Override
    public void init(AsyncMessageBroker broker) {
        this.broker = broker;

        broker.registerListener(EventType.WISHLIST_ADD_REQUESTED, handleAdd);
        broker.registerListener(EventType.WISHLIST_REMOVE_REQUESTED, handleRemove);
        broker.registerListener(EventType.WISHLIST_VIEW_REQUESTED, handleView);

        LOGGER.info("[WishlistManagement] Subsystem initialized.");
    }

    @Override
    public void start() {
    }

    @Override
    public void shutdown() {
        broker.unregisterListener(EventType.WISHLIST_ADD_REQUESTED, handleAdd);
        broker.unregisterListener(EventType.WISHLIST_REMOVE_REQUESTED, handleRemove);
        broker.unregisterListener(EventType.WISHLIST_VIEW_REQUESTED, handleView);

        LOGGER.info("[WishlistManagement] Subsystem shutdown.");
    }

    /**
     * ----------------------------
     * HANDLE ADD TO WISHLIST
     * -----------------------------
     */
    private CompletableFuture<Void> onAddRequested(Message message) {
        return CompletableFuture.runAsync(() -> {

            if (!(message.getPayload() instanceof WishlistAddRequest req)) {
                return;
            }

            // Check stock
            Item item = itemRepo.findById(req.getItemId());
            if (item == null || item.getStockQuantity() <= 0) {
                broker.publish(EventType.WISHLIST_ADD_FAILED, "Item not available");
                return;
            }

            Wishlist existing = wishlistRepo.findByCustomerAndItem(req.getUserId(), req.getItemId());
            if (existing != null) {
                broker.publish(EventType.WISHLIST_ADD_FAILED, "Item already in wishlist");
                return;
            }

            // Add wishlist entry
            Wishlist entry = new Wishlist(
                    0, // ID will be auto-generated by database
                    req.getUserId(),
                    req.getItemId(),
                    req.getQuantity(),
                    System.currentTimeMillis());

            wishlistRepo.insert(entry);

            broker.publish(EventType.WISHLIST_ADD_SUCCESS, entry);
        });
    }

    /**
     * ----------------------------
     * HANDLE REMOVE FROM WISHLIST
     * -----------------------------
     */
    private CompletableFuture<Void> onRemoveRequested(Message message) {
        return CompletableFuture.runAsync(() -> {

            if (!(message.getPayload() instanceof WishlistRemoveRequest req)) {
                LOGGER.warning("[Wishlist] Invalid DTO for remove request");
                return;
            }

            LOGGER.info("[Wishlist] Remove requested: user=" + req.getUserId()
                    + ", item=" + req.getItemId());

            Wishlist found = wishlistRepo.findByCustomerAndItem(req.getUserId(), req.getItemId());

            if (found == null) {
                broker.publish(EventType.WISHLIST_REMOVE_FAILED,
                        "Item not found in wishlist.");
                return;
            }

            wishlistRepo.delete(found.getId());

            broker.publish(EventType.WISHLIST_REMOVE_SUCCESS, found);
            LOGGER.info("[Wishlist] Removed successfully.");
        });
    }

    /**
     * ----------------------------
     * HANDLE VIEW WISHLIST
     * -----------------------------
     */
    private CompletableFuture<Void> onViewRequested(Message message) {
        return CompletableFuture.runAsync(() -> {

            int userId;
            Object payload = message.getPayload();

            System.out.println("[WishlistManagement] Received WISHLIST_VIEW_REQUESTED, payload type: " +
                    (payload != null ? payload.getClass().getSimpleName() : "null") + ", value: " + payload);

            if (payload instanceof com.common.dto.wishlist.WishlistViewRequest req) {
                userId = req.getUserId();
                System.out.println("[WishlistManagement] Extracted userId from WishlistViewRequest: " + userId);
            } else if (payload instanceof Integer) {
                userId = (Integer) payload;
                System.out.println("[WishlistManagement] Extracted userId from Integer: " + userId);
            } else {
                LOGGER.warning(
                        "[Wishlist] Invalid DTO for view request - expected WishlistViewRequest or Integer, got: "
                                + (payload != null ? payload.getClass().getSimpleName() : "null"));
                System.out.println("[WishlistManagement] Publishing empty list due to invalid payload");
                broker.publish(EventType.WISHLIST_DETAILS_RETURNED, new ArrayList<>());
                return;
            }

            LOGGER.info("[Wishlist] View requested for user=" + userId);

            List<Wishlist> wishlistItems = wishlistRepo.findByCustomerId(userId);
            System.out.println(
                    "[WishlistManagement] Found " + wishlistItems.size() + " wishlist items for user " + userId);

            broker.publish(EventType.WISHLIST_DETAILS_RETURNED, wishlistItems);
            System.out.println(
                    "[WishlistManagement] Published WISHLIST_DETAILS_RETURNED with " + wishlistItems.size() + " items");
        });
    }
}